blank_issues_enabled: false
contact_links:
  - name: 💬 Github Discussion
    url: https://github.com/aimok04/lovelace-material-components/discussions/new?category=ideas
    about: Start a new discussion to share your ideas or ask questions.
